### PR TITLE
Patch for ROS 2 Galactic

### PR DESCRIPTION
**Pull request by hello-chintan**
Cleared error:
in generate_launch_description
    Node(
TypeError: __init__() missing 1 required keyword-only argument: 'executable'

### CODE REVIEW

**Comment by vinicentus** [comment]
Would this close #1 and #2?

**Comment by hello-chintan** [comment]
Yes, this should fix them.

**Comment by moonlight0-0** [comment]
Does ROS2 galactic support now?

**Comment by YXGuan** [comment]
Yep, this should fix the issue! Thanks Chintan!

**Comment by deyouslamtec** [comment]
has been merged

**Pull request closed without merging**
